name: uni_links2
version: 0.6.0+2
homepage: https://github.com/ericmartineau/uni_links/tree/master/uni_links
description: Flutter plugin for accepting incoming links - App/Deep Links (Android), Universal Links and Custom URL schemes (iOS).
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.1 <3.0.0'
dependencies: 
  uni_links2_platform_interface:
    git:
      url: http://github.com/KR-moqod/uni_links.git
      path: uni_links_platform_interface
      ref: 9c0e4866bcd4f8c9e0096ab54661335716f4ea1f
  flutter: 
    sdk: flutter
dev_dependencies: 
  pedantic: ^1.11.0
  flutter_test: 
    sdk: flutter
flutter: 
  plugin: 
    platforms: 
      android: 
        package: name.avioli.unilinks
        pluginClass: UniLinksPlugin
      ios: 
        pluginClass: UniLinksPlugin
